baseURL = 'https://ntatsuya.com/'
title = "Naka-Tabi"

theme = 'puppet'

copyright = 'Copyright © 2023 Tatsuya Nakajima'
paginate = 3
languageCode = 'ja'
defaultContentLanguage = "ja"

hasCJKLanguage = true

ignoreErrors = ["error-remote-getjson"]

googleAnalytics = "G-39PQQB4CK3"

[language]
lang = 'ja'

[outputs]
home = ["HTML", "JSON", "RSS"]

[taxonomies]
category = "categories"
tag = "tags"
series = "series"

[markup]
[markup.highlight]
noClasses = true
codeFences = true
guessSyntax = true
lineNos = true
lineNumbersInTable = false
style = "dracula"

[markup.goldmark.renderer]
unsafe = true

[menu]
[[menu.main]]
identifier = "home"
name = "Home"
url = "/"
weight = -100

[[menu.main]]
identifier = "about"
name = "About"
url = "https://tatsuyanakajima.com/about.html"
weight = 50

[[menu.main]]
identifier = "portfolio"
name = "Portfolio"
url = "https://tatsuyanakajima.com/"
weight = 100

[[menu.main]]
identifier = "instagram"
name = "Instagram"
url = "https://www.instagram.com/ntmkc951/"
weight = 150

[params]
author = "nakajima"
#description = "植物、鳥とか"
keywords = "blog,developer,personal"
img_home = "img/IMG_1055.jpg"
img_404 = "img/_MG_3824.jpg"

useFaviconGenerator = false

custom_js = [ "js/clarity.js" ]
custom_css = []

[params.sidebar]
enable = true
# Overwritten by your gravatar image if `gravatarEmail` is filled
avatar = "img/icon.jpg"

[params.social]
twitter = "xaMIEPc1vpA1xpu"
instagram = "ntmkc951"
rss = true


[[params.friends]]
name = "島根大学ものづくり部 Pim"
url = "https://pim-shimane.com/"

